apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp
  name: webapp
spec:
  containers:
  - image: learntechacr.azurecr.io/myrepo001/nginximage:v1
    name: webapp
  restartPolicy: Always
  # imagePullSecrets:
  #    - name: docsec 
