FROM nginx:latest 
COPY src/. /usr/share/nginx/html
# FROM alpine/helm:3.7.1 
# RUN apk add --no-cache \
#     curl \
#     python3 \
#     bash
# RUN apk add --no-cache --virtual=build gcc libffi-dev musl-dev openssl-dev python3-dev make \
#     && python3 -m ensurepip \
#     && pip3 install --no-cache-dir --upgrade pip \
#     && pip3 install --no-cache-dir azure-cli \
#     && apk del --no-cache build

     
 
